const tasksSelect = [
  {
    id: 1,
    translate: 'Я был очень занят',
    question: 'I ___ was so busy',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'was',
  },
  {
    id: 2,
    translate: 'Мы были вместе',
    question: 'We ___ together',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'were',
  },
  {
    id: 3,
    translate: 'Ты был прав',
    question: 'You ___ right',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'were',
  },
  {
    id: 4,
    translate: 'Они были в другом городе',
    question: 'They ___ in the other city',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'were',
  },
  {
    id: 5,
    translate: 'Он был на работе',
    question: 'He ___ at work',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'was',
  },
  {
    id: 6,
    translate: 'Она была так счастлива',
    question: 'She ___ so happy',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'was',
  },
  {
    id: 7,
    translate: 'Это было очень важно',
    question: 'It ___ so important',
    variant1: 'was',
    variant2: 'were',
    variant3: 'is',
    variant4: 'are',
    correct: 'was',
  },
  {
    id: 8,
    translate: 'Это было действительно интересно',
    question: '',
    variant1: 'It were really interesting',
    variant2: 'It is really interesting',
    variant3: 'It was really interesting',
    variant4: 'It are really interesting',
    correct: 'It was really interesting',
  },
  {
    id: 9,
    translate: 'Я был очень счастлив',
    question: '',
    variant1: 'I was so funny',
    variant2: 'I was so nervous',
    variant3: 'I were so happy',
    variant4: 'I was so happy',
    correct: 'I was so happy',
  },
  {
    id: 10,
    translate: 'Ты был совершенно прав',
    question: '',
    variant1: 'You were completely right',
    variant2: 'You were completely wrong',
    variant3: 'You was completely right',
    variant4: 'You was completely wrong',
    correct: 'You were completely right',
  },
];

export default tasksSelect;
