const tasksSelect = [
  {
    id: 1,
    translate: 'Он сказал, что выиграл',
    question: 'He said, that he ___',
    variant1: 'win',
    variant2: 'won',
    variant3: 'had won',
    variant4: 'has won',
    correct: 'had won',
  },
  {
    id: 2,
    translate: 'Я знал, что это уже произошло',
    question: 'I knew that it ___',
    variant1: 'has almost happened',
    variant2: 'have already happened',
    variant3: 'had almost happened',
    variant4: 'had already happened',
    correct: 'had already happened',
  },
  {
    id: 3,
    translate: 'Я был так счастлив, потому что сдал тест успешно',
    question: 'I was so happy because I ___',
    variant1: 'have passed the test successfully',
    variant2: 'had passed the test successfully',
    variant3: 'have pass the test successfully',
    variant4: 'had pass the test successfully',
    correct: 'had passed the test successfully',
  },
  {
    id: 4,
    translate: 'Когда я пришел домой, она уже приготовила ужин',
    question: 'When I came home, ___',
    variant1: 'she has already cooked dinner',
    variant2: 'she had already cooked dinner',
    variant3: 'she already had cooked dinner',
    variant4: 'she already has cooked dinner',
    correct: 'she had already cooked dinner',
  },
  {
    id: 5,
    translate:
      'К тому времени, как я окончил школу, я уже достиг среднего уровня в английском',
    question:
      'By the time I finished school, I ___ the Intermediate level in English',
    variant1: 'had already reached',
    variant2: 'have already reached',
    variant3: 'had already arrived',
    variant4: 'have already arrived',
    correct: 'had already reached',
  },
  {
    id: 6,
    translate: 'Я уже ушел из дома к тому времени, как они прибыли',
    question: 'I ___ home by the time they arrived',
    variant1: 'had already come',
    variant2: 'had already left',
    variant3: 'had already leave',
    variant4: 'had already quit',
    correct: 'had already left',
  },
  {
    id: 7,
    translate: 'Я понял, что сделал ошибку',
    question: 'I ___ that I had made a mistake',
    variant1: 'understand',
    variant2: 'had understood',
    variant3: 'understood',
    variant4: 'have understood',
    correct: 'understood',
  },
  {
    id: 8,
    translate: 'Он сказал, что провалил тест',
    question: 'He ___ he ___ the test',
    variant1: 'told, had failed',
    variant2: 'said, has failed',
    variant3: 'told, has failed',
    variant4: 'said, had failed',
    correct: 'said, had failed',
  },
  {
    id: 9,
    translate: 'Она сказала мне, что никто не заметил это',
    question: 'She ___ me that no one ___ it',
    variant1: 'said, had noticed',
    variant2: 'told, had noticed',
    variant3: "said, hadn't noticed",
    variant4: "told, hadn't noticed",
    correct: 'told, had noticed',
  },
  {
    id: 10,
    translate: 'Я знал, что они обманули ее',
    question: 'I ___ that they ___ her',
    variant1: 'knew, had deceived',
    variant2: 'known, had deceived',
    variant3: 'knew, has deceived',
    variant4: 'knew, have deceived',
    correct: 'knew, had deceived',
  },
];

export default tasksSelect;
