const tasksSelect = [
  {
    id: 1,
    question: 'Water from the sky!',
    variant1: 'rain',
    variant2: 'fog',
    variant3: 'warm',
    variant4: 'storm',
    correct: 'rain',
  },
  {
    id: 2,
    question: 'Quite hot, but not too hot',
    variant1: 'hot',
    variant2: 'warm',
    variant3: 'cold',
    variant4: 'dry',
    correct: 'warm',
  },
  {
    id: 3,
    question: 'When the temperature is low, it is ...',
    variant1: 'cloud',
    variant2: 'sun',
    variant3: 'cold',
    variant4: 'wet',
    correct: 'cold',
  },
  {
    id: 4,
    question: 'Moving air. It makes trees and things move.',
    variant1: 'wet',
    variant2: 'wind',
    variant3: 'warm',
    variant4: 'fog',
    correct: 'wind',
  },
  {
    id: 5,
    question: 'White or grey shapes in the sky',
    variant1: 'hot',
    variant2: 'storm',
    variant3: 'wind',
    variant4: 'cloud',
    correct: 'cloud',
  },
  {
    id: 6,
    question: 'When it rains, everything is ...',
    variant1: 'wet',
    variant2: 'cloud',
    variant3: 'wind',
    variant4: 'fog',
    correct: 'wet',
  },
  {
    id: 7,
    question: 'The big, yellow, hot thing in the sky',
    variant1: 'cloud',
    variant2: 'sun',
    variant3: 'storm',
    variant4: 'rain',
    correct: 'sun',
  },
  {
    id: 8,
    question: 'Water vapour in the air near the ground',
    variant1: 'fog',
    variant2: 'wet',
    variant3: 'sun',
    variant4: 'rain',
    correct: 'fog',
  },
  {
    id: 9,
    question: 'Thunder and lightning. Bad weather for boats!',
    variant1: 'rain',
    variant2: 'wet',
    variant3: 'cloud',
    variant4: 'storm',
    correct: 'storm',
  },
  {
    id: 10,
    question: 'If there is no rain, the ground is ...',
    variant1: 'sun',
    variant2: 'wet',
    variant3: 'dry',
    variant4: 'wind',
    correct: 'dry',
  },
];

export default tasksSelect;
