const tasksSelect = [
  {
    id: 1,
    question: 'A ___ is a long, thin and orange vegetable.',
    variant1: 'lettuce',
    variant2: 'carrot',
    variant3: 'onion',
    variant4: 'pepper',
    correct: 'carrot',
  },
  {
    id: 2,
    question:
      'A ___ grows in the ground and we must cook it before we eat it. It is used to make chips.',
    variant1: 'cucumber',
    variant2: 'sweetcorn',
    variant3: 'potato',
    variant4: 'tomato',
    correct: 'potato',
  },
  {
    id: 3,
    question: 'A ___ is a red and round vegetable. We can eat it in salads.',
    variant1: 'pea',
    variant2: 'lettuce',
    variant3: 'onion',
    variant4: 'tomato',
    correct: 'tomato',
  },
  {
    id: 4,
    question: 'An ___ is round and light brown. It can make you cry!',
    variant1: 'onion',
    variant2: 'tomato',
    variant3: 'potato',
    variant4: 'carrot',
    correct: 'onion',
  },
  {
    id: 5,
    question: ' A ___ is a vegetable that has thick green leaves.',
    variant1: 'cucumber',
    variant2: 'onion',
    variant3: 'cabbage',
    variant4: 'cauliflower',
    correct: 'cabbage',
  },
  {
    id: 6,
    question: 'A ___ is small, round and green. They grow in large numbers.',
    variant1: 'sweetcorn',
    variant2: 'pea',
    variant3: 'potato',
    variant4: 'lettuce',
    correct: 'pea',
  },
  {
    id: 7,
    question: 'A ___ has light green leaves that we eat in salads.',
    variant1: 'pea',
    variant2: 'aubergine',
    variant3: 'cauliflower',
    variant4: 'lettuce',
    correct: 'lettuce',
  },
  {
    id: 8,
    question: 'A ___ is long and green. We can eat it in salads or sandwiches.',
    variant1: 'cucumber',
    variant2: 'lettuce',
    variant3: 'aubergine',
    variant4: 'cabbage',
    correct: 'cucumber',
  },
  {
    id: 9,
    question: '___ can be red, green or yellow. We eat them in salads.',
    variant1: 'pea',
    variant2: 'carrot',
    variant3: 'cabbage',
    variant4: 'pepper',
    correct: 'pepper',
  },
  {
    id: 10,
    question: '___ is yellow. The small parts are the same size as peas.',
    variant1: 'onion',
    variant2: 'lettuce',
    variant3: 'sweetcorn',
    variant4: 'aubergine',
    correct: 'sweetcorn',
  },
];

export default tasksSelect;
